CREATE DATABASE SP_Medical_Group
GO

USE SP_Medical_Group
GO

--ESPECIALIDADE
CREATE TABLE Especialidade (
 IdEspecialidade SMALLINT PRIMARY KEY IDENTITY,
 NomeEspecialidade VARCHAR(100) NOT NULL
);
GO

--TIPO DE USUÁRIO
CREATE TABLE TipoUsuario (
 IdTipoUsuario TINYINT PRIMARY KEY IDENTITY,
 TituloTipoUsuario VARCHAR(30) NOT NULL
);
GO

--SITUAÇÃO
CREATE TABLE Situacao (
 IdSituacao TINYINT PRIMARY KEY IDENTITY,
 Situacao  VARCHAR(15) NOT NULL
);
GO

--CLINICA
CREATE TABLE Clinica (
 IdClinica SMALLINT PRIMARY KEY IDENTITY,
 NomeClinica VARCHAR(100) NOT NULL,
 Endereço VARCHAR(200) NOT NULL,
 CNPJ VARCHAR(18) UNIQUE NOT NULL,
 RazaoSocial VARCHAR (50) NOT NULL,
 HorarioAbertura TIME NOT NULL,
 HorarioFechamento TIME NOT NULL
);
GO

--USUARIO
CREATE TABLE Usuario (
 IdUsuario SMALLINT PRIMARY KEY IDENTITY,
 IdTipoUsuario TINYINT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
 Email VARCHAR(256) UNIQUE NOT NULL,
 Senha VARCHAR(25) NOT NULL CHECK( len(Senha) >= 6) 
);
GO

--IMAGEM DO USUARIO
CREATE TABLE ImagemUsuario (
Id SMALLINT PRIMARY KEY IDENTITY,
IdUsuario SMALLINT FOREIGN KEY REFERENCES Usuario(IdUsuario),
Binario VARBINARY(MAX) NOT NULL,
MymeType VARCHAR(30) NOT NULL,
NomeArquivo VARCHAR(250) NOT NULL,
DataInclusao DATETIME DEFAULT GETDATE() NOT NULL
);
GO

--PACIENTE
CREATE TABLE Paciente (
 IdPaciente SMALLINT PRIMARY KEY IDENTITY,
 IdUsuario SMALLINT FOREIGN KEY REFERENCES Usuario(IdUsuario),
 NomePaciente VARCHAR(70) NOT NULL,
 RG VARCHAR(15) NOT NULL,
 CPF VARCHAR(14) UNIQUE NOT NULL,
 Endereço VARCHAR (200) NOT NULL,
 DataNascimento DATE NOT NULL,
 Telefone VARCHAR(15)
);
GO

--MEDICO
CREATE TABLE Medico (
 IdMedico TINYINT PRIMARY KEY IDENTITY,
 IdUsuario SMALLINT FOREIGN KEY REFERENCES Usuario(IdUsuario),
 IdClinica SMALLINT FOREIGN KEY REFERENCES Clinica(IdClinica),
 IdEspecialidade SMALLINT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade),
 NomeMedico VARCHAR(70) NOT NULL,
 CRM VARCHAR(8) UNIQUE NOT NULL
);
GO

--CONSULTA
CREATE TABLE Consulta(
 IdConsulta TINYINT PRIMARY KEY IDENTITY,
 IdPaciente SMALLINT FOREIGN KEY REFERENCES Paciente(IdPaciente),
 IdMedico TINYINT FOREIGN KEY REFERENCES Medico(IdMedico),
 IdSituacao TINYINT FOREIGN KEY REFERENCES Situacao(IdSituacao) DEFAULT(1),
 DataConsulta DATETIME NOT NULL,
 Descricao VARCHAR(500)
);

DROP DATABASE SP_Medical_Group

